/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * an    @Override
    public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Insets getBorderInsets(Component c) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean isBorderOpaque() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
d open the template in the editor.
 */
package GUI;

import static java.awt.Color.WHITE;
import java.awt.event.KeyEvent;
import java.io.StringReader;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.plaf.ColorUIResource;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.Stack;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import main.Main;

/**
 *
 * @author luisd
 */
public class Interfaz extends javax.swing.JFrame {
    // falta metodo para cargar todo al abrir un archivo
    public static String texto_consola = "";
    public static String fname = "NewFile";
    public static String path = "NewFile";
    public static String funcion = "";
    public static boolean generated = false;
    public static Stack<String> expName = new Stack<>();
            
    /**
     * Creates new form NewJFrame
     */
    public Interfaz() {
        UIManager.put("TextPane.caretForeground", new ColorUIResource(WHITE));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEntrada = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        btnAutomatas = new javax.swing.JButton();
        btnAnalizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        imgPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        VentanaMenu = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        AboutMenu = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        BtnExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGEXIVE");
        setBackground(new java.awt.Color(66, 66, 66));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(41, 47, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1170, 645));

        jScrollPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jScrollPane1KeyPressed(evt);
            }
        });

        txtEntrada.setBackground(new java.awt.Color(20, 29, 38));
        txtEntrada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 47, 47)));
        Border border = txtEntrada.getBorder();
        Border margin = new EmptyBorder(5,10,10,5);
        txtEntrada.setBorder(javax.swing.BorderFactory.createCompoundBorder(border, margin));
        txtEntrada.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtEntrada.setForeground(new java.awt.Color(211, 211, 211));
        txtEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEntradaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtEntrada);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Cadena de entrada");

        btnAutomatas.setBackground(new java.awt.Color(36, 52, 71));
        btnAutomatas.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnAutomatas.setForeground(new java.awt.Color(51, 51, 51));
        btnAutomatas.setText("Generar autómatas");
        btnAutomatas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 52, 71), 2));
        btnAutomatas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAutomatas.setFocusable(false);
        btnAutomatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomatasActionPerformed(evt);
            }
        });
        btnAutomatas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAutomatasKeyPressed(evt);
            }
        });

        btnAnalizar.setBackground(new java.awt.Color(36, 52, 71));
        btnAnalizar.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnAnalizar.setForeground(new java.awt.Color(51, 51, 51));
        btnAnalizar.setText("Analizar entradas");
        btnAnalizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 52, 71), 2));
        btnAnalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnalizar.setFocusable(false);
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });
        btnAnalizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAnalizarKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Salida");

        txtSalida.setEditable(false);
        txtSalida.setBackground(new java.awt.Color(20, 29, 38));
        txtSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 47, 47)));
        Border border2 = txtSalida.getBorder();
        Border margin2 = new EmptyBorder(5,10,10,10);
        txtSalida.setBorder(javax.swing.BorderFactory.createCompoundBorder(border2, margin2));
        txtSalida.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtSalida.setForeground(new java.awt.Color(211, 211, 211));
        txtSalida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSalidaKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(txtSalida);

        jScrollPane2.setBackground(new java.awt.Color(20, 29, 38));
        jScrollPane2.setBorder(new EmptyBorder(10,5,10,5));

        jTree.setBackground(new java.awt.Color(20, 29, 38));
        jTree.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("JTree");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Árboles");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Siguientes");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Transiciones");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Autómatas");
        treeNode1.add(treeNode2);
        jTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree.setRootVisible(false);
        jTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeMouseClicked(evt);
            }
        });
        jTree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTreeKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTree);

        jSeparator1.setBackground(new java.awt.Color(20, 29, 38));
        jSeparator1.setForeground(new java.awt.Color(20, 29, 38));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        imgPanel.setBackground(new java.awt.Color(20, 29, 38));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout imgPanelLayout = new javax.swing.GroupLayout(imgPanel);
        imgPanel.setLayout(imgPanelLayout);
        imgPanelLayout.setHorizontalGroup(
            imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );
        imgPanelLayout.setVerticalGroup(
            imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(imgPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel1))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(btnAutomatas, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(40, 40, 40)))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAutomatas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        BarraMenu.setBackground(new java.awt.Color(60, 64, 65));
        BarraMenu.setFocusable(false);

        FileMenu.setForeground(java.awt.Color.darkGray);
        FileMenu.setText("Archivo");
        FileMenu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/open-file-icon.png"))); // NOI18N
        jMenuItem1.setText("  Abrir                                       Ctrl+A");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        FileMenu.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/floppy-icon.png"))); // NOI18N
        jMenuItem2.setText("  Guardar                                  Ctrl+S");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        FileMenu.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Save-icon.png"))); // NOI18N
        jMenuItem3.setText("  Guardar como...                   Ctrl+Shift+S");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        FileMenu.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/app-json-icon.png"))); // NOI18N
        jMenuItem4.setText("  Abrir directorio JSON");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        FileMenu.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/close-icon.png"))); // NOI18N
        jMenuItem5.setText("  Cerrar archivo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        FileMenu.add(jMenuItem5);

        BarraMenu.add(FileMenu);

        VentanaMenu.setForeground(java.awt.Color.darkGray);
        VentanaMenu.setText("Ventana");
        VentanaMenu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Window-new-icon.png"))); // NOI18N
        jMenuItem7.setText("  Nueva ventana                     Ctrl+N");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        VentanaMenu.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Close-2-icon.png"))); // NOI18N
        jMenuItem8.setText("  Cerrar ventana                      Alt+W");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        VentanaMenu.add(jMenuItem8);

        BarraMenu.add(VentanaMenu);

        AboutMenu.setForeground(java.awt.Color.darkGray);
        AboutMenu.setText("Acerca de");
        AboutMenu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem6.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem6.setText("<html>REGEXIVE &copy; 2021 OLC1<br/>"
            + "Autor: Luis Danniel Ernesto Castellanos Galindo<br/>"
            + "Carnet: 201902238");
        jMenuItem6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuItem6.setEnabled(false);
        AboutMenu.add(jMenuItem6);

        BarraMenu.add(AboutMenu);

        BtnExit.setForeground(java.awt.Color.darkGray);
        BtnExit.setText("Salir");
        BtnExit.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        BtnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnExitMouseClicked(evt);
            }
        });
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        BarraMenu.add(BtnExit);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1178, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //Open file
        if (!"NewFile".equals(fname)) {
            if (JOptionPane.showConfirmDialog(this, "Perderá todos los datos que no haya guardado", " ¿Está seguro?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                openFile();
            }
        } else {
            openFile();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //Update file
        if ("NewFile".equals(fname)) {
            saveAs();
        }
        else{
            File file = new File(path);
            try (FileWriter escritor = new FileWriter(file)) {
                escritor.write(txtEntrada.getText());
            } catch (IOException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_A) {
            //Open method
            if (!"NewFile".equals(fname)) {
                if (JOptionPane.showConfirmDialog(this, "Perderá todos los datos que no haya guardado", " ¿Está seguro?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    openFile();
                }
            } else {
                openFile();
            }
        } else if (evt.isControlDown() && !evt.isShiftDown() && evt.getKeyCode() == KeyEvent.VK_S) {
            //Update file
            if ("NewFile".equals(fname)) {
                saveAs();
            } else {
                File file = new File(path);
                try (FileWriter escritor = new FileWriter(file)) {
                    escritor.write(txtEntrada.getText());
                } catch (IOException ex) {
                    Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else if (evt.isControlDown() && evt.isShiftDown() && evt.getKeyCode() == KeyEvent.VK_S) {
            saveAs();
        } else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_N) {
            try {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                Interfaz vp = new Interfaz();
                vp.setVisible(true);
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (evt.isAltDown() && evt.getKeyCode() == KeyEvent.VK_W) {
            if (!"NewFile".equals(fname)) {
                if (JOptionPane.showConfirmDialog(this, "Perderá todos los datos que no haya guardado", " ¿Está seguro?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    this.dispose();
                }
            } else {
                this.dispose();
            }
        }
    }//GEN-LAST:event_formKeyPressed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // Abrir directorio
        try {
            Desktop desktop = Desktop.getDesktop();
            File dirToOpen = new File("C:\\Users\\luisd\\Documents\\NetBeansProjects\\REGEXIVE\\src\\REPORTES\\SALIDAS_201902238");
            desktop.open(dirToOpen);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExitMouseClicked
        if (JOptionPane.showConfirmDialog(this,"¿Seguro que quieres salir de todas las ventanas?","   Salir",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_BtnExitMouseClicked

    private void btnAutomatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomatasActionPerformed
        if ("".equals(txtEntrada.getText())) {
            JOptionPane.showMessageDialog(this, " Debe digitar una entrada válida", " Archivo vacío", JOptionPane.WARNING_MESSAGE);
        } else {
            funcion = "GENERAR AUTOMATAS";
            texto_consola = "";
            Modelos.Errores.lista_errores.clear();
            expName.clear();
            txtSalida.setText("");
//        try {
            String path = txtEntrada.getText();
            Analizadores.parser sintactico;
            sintactico = new Analizadores.parser(new Analizadores.Lexico(new StringReader(path)));
            sintactico.parse();
            Modelos.Errores.reportarErrores(fname);
            txtSalida.setText(texto_consola);
            addTreeNode();
//        } catch (Exception e) {
//            txtSalida.setText(e.toString());
//        }
            generated = true;
        }
    }//GEN-LAST:event_btnAutomatasActionPerformed
    
    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        if (generated) {
            funcion = "ANALIZAR ENTRADAS";
        texto_consola="";
        Modelos.Errores.lista_errores.clear();
        txtSalida.setText("");
//        try {
            String path = txtEntrada.getText();
            Analizadores.parser sintactico;
            sintactico = new Analizadores.parser(new Analizadores.Lexico(new StringReader(path)));
            sintactico.parse();
            Modelos.Errores.reportarErrores(fname);
            txtSalida.setText(texto_consola);
//        } catch (Exception e) {
//            txtSalida.setText(e.toString());
//        }
        } else {
            JOptionPane.showMessageDialog(this, "No se encuentran autómatas generados\n", " Intente de nuevo", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void txtEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntradaKeyPressed
        formKeyPressed(evt);
    }//GEN-LAST:event_txtEntradaKeyPressed

    private void jScrollPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane1KeyPressed
        formKeyPressed(evt);
    }//GEN-LAST:event_jScrollPane1KeyPressed

    private void txtSalidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalidaKeyPressed
        formKeyPressed(evt);
    }//GEN-LAST:event_txtSalidaKeyPressed

    private void btnAutomatasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAutomatasKeyPressed
        formKeyPressed(evt);
    }//GEN-LAST:event_btnAutomatasKeyPressed

    private void btnAnalizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAnalizarKeyPressed
        formKeyPressed(evt);
    }//GEN-LAST:event_btnAnalizarKeyPressed

    private void jTreeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTreeKeyPressed
        formKeyPressed(evt);
    }//GEN-LAST:event_jTreeKeyPressed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        //Close file
        if (!"NewFile".equals(fname)) {
            if (JOptionPane.showConfirmDialog(this, "Perderá todos los datos que no haya guardado", " ¿Está seguro?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                closeFile();
            }
        } else {
            closeFile();
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreeMouseClicked
        try {
            if (evt.getClickCount() >= 1) {
                DefaultMutableTreeNode node = (DefaultMutableTreeNode) jTree.getLastSelectedPathComponent();
                if (node == null) {
                    return;
                }
                Desktop desktop = Desktop.getDesktop();
                switch (node.getParent().toString()) {
                    case "Árboles":
                        if (evt.getClickCount() == 1) {
                            BufferedImage image = ImageIO.read(new File("src/GUI/IMAGENES/ARBOLES/" + node.toString() + ".png"));
                            jLabel3.setIcon(new ImageIcon(image));
                        }
                        if (evt.getClickCount() == 2) {
                            desktop.open(new File("src\\REPORTES\\ARBOLES_201902238\\" + node.toString() + ".svg"));
                        }
                        break;
                    case "Siguientes":
                        if (evt.getClickCount() == 1) {
                            BufferedImage image = ImageIO.read(new File("src/GUI/IMAGENES/SIGUIENTES/" + node.toString() + ".png"));
                            jLabel3.setIcon(new ImageIcon(image));
                        }
                        if (evt.getClickCount() == 2) {
                            desktop.open(new File("src\\REPORTES\\SIGUIENTES_201902238\\" + node.toString() + ".svg"));
                        }
                        break;
                    case "Transiciones":
                        if (evt.getClickCount() == 1) {
                            BufferedImage image = ImageIO.read(new File("src/GUI/IMAGENES/TRANSICIONES/" + node.toString() + ".png"));
                            jLabel3.setIcon(new ImageIcon(image));
                        }
                        if (evt.getClickCount() == 2) {
                            desktop.open(new File("src\\REPORTES\\TRANSICIONES_201902238\\" + node.toString() + ".svg"));
                        }
                        break;
                    case "Autómatas":
                        if (evt.getClickCount() == 1) {
                            System.out.println("src/GUI/IMAGENES/AFND/" + node.toString() + ".png");
                            if (node.toString().startsWith("AFND")) {
                                BufferedImage image = ImageIO.read(new File("src/GUI/IMAGENES/AFND/" + node.toString().substring(4) + ".png"));
                                jLabel3.setIcon(new ImageIcon(image));
                            } else {
                                BufferedImage image = ImageIO.read(new File("src/GUI/IMAGENES/AFD/" + node.toString().substring(3) + ".png"));
                                jLabel3.setIcon(new ImageIcon(image));
                            }
                        }
                        if (evt.getClickCount() == 2) {
                            if (node.toString().startsWith("AFND")) {
                                File f = new File("src\\REPORTES\\AFND_201902238\\" + node.toString().substring(4) + ".svg");
                                desktop.open(f);
                            } else {
                                File f = new File("src\\REPORTES\\AFD_201902238\\" + node.toString().substring(3) + ".svg");
                                desktop.open(f);
                            }
                        }
                        break;
                }
            }
        } catch (IOException e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jTreeMouseClicked

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            Interfaz vp = new Interfaz();
            vp.setVisible(true);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        saveAs();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void addTreeNode(){
        DefaultTreeModel model = (DefaultTreeModel)jTree.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode)model.getRoot();
        DefaultMutableTreeNode arboles = (DefaultMutableTreeNode)model.getChild(root, 0);
        DefaultMutableTreeNode siguientes = (DefaultMutableTreeNode)model.getChild(root, 1);
        DefaultMutableTreeNode transiciones = (DefaultMutableTreeNode)model.getChild(root, 2);
        DefaultMutableTreeNode automatas = (DefaultMutableTreeNode)model.getChild(root, 3);
        for (int i = 0; i < expName.size(); i++) {
            String x = expName.elementAt(i);
            switch (x.charAt(0)) {
                case '0':
                    arboles.add(new DefaultMutableTreeNode(x.substring(1)+"_"+fname));
                    break;
                case '1':
                    siguientes.add(new DefaultMutableTreeNode(x.substring(1)+"_"+fname));
                    break;
                case '2':
                    transiciones.add(new DefaultMutableTreeNode(x.substring(1)+"_"+fname));
                    break;
                case '3':
                    automatas.add(new DefaultMutableTreeNode("AFND"+x.substring(1)+"_"+fname));
                    break;
                case '4':
                    automatas.add(new DefaultMutableTreeNode("AFD"+x.substring(1)+"_"+fname));
                    break;
            }
        }
        model.reload(root);
    }
    
    public static void addToTree(String item, int type){
        
        GUI.Interfaz.expName.add(String.valueOf(type) + item);
    }
    
    public void closeFile(){
        txtEntrada.setText("");
        txtSalida.setText("");
        jLabel3.setIcon(null);
        DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("JTree");
        DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Árboles");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Siguientes");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Transiciones");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Autómatas");
        treeNode1.add(treeNode2);
        jTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        fname = "NewFile";
    }
    
    public void openFile(){
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("olc file", "olc"));
        fileChooser.setDialogTitle("Abrir archivo");
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            path = file.getAbsolutePath();
            String name = file.getName();
            fname = name.replaceFirst("[.][^.]+$", "");
            try {
                FileReader reader = new FileReader(path);
                try (BufferedReader br = new BufferedReader(reader)) {
                    txtEntrada.read(br, null);
                }
                txtEntrada.requestFocus();
            } catch (IOException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public void saveAs(){
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("olc file", "olc"));
        fileChooser.setDialogTitle("Guardar como...");
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            String filename = fileChooser.getSelectedFile().toString();
            if (!filename.endsWith(".olc")) {
                filename += ".olc";
            }
            File file = new File(filename);
            path = file.getAbsolutePath();
            String name = file.getName();
            fname = name.replaceFirst("[.][^.]+$", "");
            try (FileWriter escritor = new FileWriter(file)) {
                escritor.write(txtEntrada.getText());
            } catch (IOException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AboutMenu;
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenu BtnExit;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu VentanaMenu;
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnAutomatas;
    private javax.swing.JPanel imgPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTree jTree;
    private javax.swing.JTextPane txtEntrada;
    private javax.swing.JTextPane txtSalida;
    // End of variables declaration//GEN-END:variables
}
