
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int especial = 17;
  public static final int conjuntoo = 16;
  public static final int porcentajes = 7;
  public static final int lcierra = 6;
  public static final int multiplicativo = 15;
  public static final int pcoma = 3;
  public static final int lexema = 9;
  public static final int prconj = 2;
  public static final int operador = 14;
  public static final int EOF = 0;
  public static final int id = 8;
  public static final int notacionL = 10;
  public static final int deriva = 13;
  public static final int error = 1;
  public static final int notacionD = 11;
  public static final int notacionA = 12;
  public static final int dospuntos = 4;
  public static final int labre = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "prconj",
  "pcoma",
  "dospuntos",
  "labre",
  "lcierra",
  "porcentajes",
  "id",
  "lexema",
  "notacionL",
  "notacionD",
  "notacionA",
  "deriva",
  "operador",
  "multiplicativo",
  "conjuntoo",
  "especial"
  };
}

